alias mvim='/Applications/MacVim.app/Contents/MacOS/MacVim'
alias reload!='. ~/.zshrc'
alias nano='vim'
alias fix_drupal_perms='find . -type d -name files -exec chmod 777 {} \;'
alias updatedb='/usr/libexec/locate.updatedb'
alias dr='drush'
